Microservices/ps-microservices-getting-started/GloboTicket/GloboTicket.Client/Controllers/EventCatalogController.cs
using System;
using System.Threading.Tasks;
using GloboTicket.Grpc;
using GloboTicket.Web.Extensions;
using GloboTicket.Web.Models;
using GloboTicket.Web.Models.Api;
using GloboTicket.Web.Models.View;
using GloboTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace GloboTicket.Web.Controllers
{
    public class EventCatalogController : Controller
    {
        private readonly Events.EventsClient eventCatalogService;


        public EventCatalogController(Events.EventsClient eventCatalogService)
        {
            this.eventCatalogService = eventCatalogService;
        }

        public async Task<IActionResult> Index(Guid categoryId)
        {


            var getCategories = eventCatalogService.GetAllCategoriesAsync(new GetAllCategoriesRequest());

            var getEvents = categoryId == Guid.Empty ?
                eventCatalogService.GetAllAsync(new GetAllEventsRequest()) :
                eventCatalogService.GetAllByCategoryIdAsync(new GetAllEventsByCategoryIdRequest { CategoryId = categoryId.ToString() }) ;



            await Task.WhenAll(new Task[] {getCategories.ResponseAsync, getEvents.ResponseAsync});

    

            return View(
                new EventListModel
                {
                    Events = getEvents.ResponseAsync.Result.Events,
                    Categories = getCategories.ResponseAsync.Result.Categories,
                    SelectedCategory = categoryId
                }
            );
        }

        [HttpPost]
        public IActionResult SelectCategory([FromForm]Guid selectedCategory)
        {
            return RedirectToAction("Index", new { categoryId = selectedCategory });
        }

        public async Task<IActionResult> Detail(Guid eventId)
        {
            var ev = await eventCatalogService.GetByEventIdAsync(new GetByEventIdRequest { EventId= eventId.ToString() });
            return View(ev.Event);
        }
    }
}

Microservices/ps-microservices-getting-started/GloboTicket/GloboTicket.Client/Controllers/ShoppingBasketController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using GloboTicket.Messages;
using GloboTicket.Web.Extensions;
using GloboTicket.Web.Models;
using GloboTicket.Web.Models.Api;
using GloboTicket.Web.Models.View;
using GloboTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;

using Rebus.Bus;

namespace GloboTicket.Web.Controllers
{
    public class ShoppingBasketController : Controller
    {
        private readonly IShoppingBasketService basketService;
        private readonly Settings settings;
        private readonly IBus bus;

        public ShoppingBasketController(IShoppingBasketService basketService, Settings settings,IBus bus)
        {
            this.basketService = basketService;
            this.settings = settings;
            this.bus = bus;
        }

        public async Task<IActionResult> Index()
        {
            var basketLines = await basketService.GetLinesForBasket(Request.Cookies.GetCurrentBasketId(settings));
            var lineViewModels = basketLines.Select(bl => new BasketLineViewModel
            {
                LineId = bl.BasketLineId,
                EventId = bl.EventId,
                EventName = bl.Event.Name,
                Date = bl.Event.Date,
                Price = bl.Price,
                Quantity = bl.TicketAmount
            }
            );
            return View(lineViewModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLine(BasketLineForCreation basketLine)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            var newLine = await basketService.AddToBasket(basketId, basketLine);
            Response.Cookies.Append(settings.BasketIdCookieName, newLine.BasketId.ToString());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateLine(BasketLineForUpdate basketLineUpdate)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            await basketService.UpdateLine(basketId, basketLineUpdate);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveLine(Guid lineId)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(settings);
            await basketService.RemoveLine(basketId, lineId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Pay()
        {
            var basketId=Request.Cookies.GetCurrentBasketId(settings);
            await bus.Send(new PaymentRequestMessage { BasketId = basketId });
             return View("Thanks");
        }
    }
}

Microservices/ps-microservices-getting-started/GloboTicket/GloboTicket.Client/Views/EventCatalog/Detail.cshtml
@model GloboTicket.Grpc.Event
<div class="row mt-5">
    <div class="col-md-4">
        <img src="@Model.ImageUrl" class="detailImage" alt="Artist pic" />
    </div>
    <div class="col-md-6 ml-1">
        <div class="row">
            <div class="columnHeader">@Model.CategoryName.ToUpper()</div>
        </div>
        <div class="row mt-2 bold">
            <h1>@Model.Name</h1>
        </div>
        <div class="row mt-2">
            <h3>@Model.Artist</h3>
        </div>
        <div class="row mt-3 mt-4 bold">
            <h3>@Model.Date.ToDateTime().ToShortDateString()</h3>
        </div>
        <div class="row mt-4">
            @Model.Description
        </div>
        <div class="row mt-5">
            <h3><span class="bold">$@Model.Price</span></h3><span class="mt-1">&nbsp;&nbsp;&nbsp; PER TICKET</span>
        </div>
    </div>
</div>
<div class="row mt-5">
    <div class="col">
        <hr />
    </div>
</div>
<div class="row mt-4">
    <div class="col offset-4">
        <form class="form" asp-action="AddLine" asp-controller="ShoppingBasket">
            <div class="row">
                <label class="columnHeader mt-2">QUANTITY:</label>
                <select name="TicketAmount" class="ml-5 w-25">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <input asp-for="EventId" type="hidden" />
                <input asp-for="Price" type="hidden" />
                <button type="submit" class="btn btn-primary ml-4">PLACE ORDER</button>
            </div>
        </form>
    </div>
</div>

Microservices/ps-microservices-getting-started/GloboTicket/GloboTicket.Client/Views/EventCatalog/Index.cshtml
@model GloboTicket.Web.Models.View.EventListModel

@{
    var categoryListItems = Model.Categories.Select(c =>
        new SelectListItem { Value = c.CategoryId.ToString(), Text = c.Name }
    ).ToList();
    categoryListItems.Insert(0, new SelectListItem { Text = "All" });
}

<div class="row mt-5 mb-3">
    <form asp-action="SelectCategory" method="post">
        <select asp-for="SelectedCategory" asp-items="categoryListItems"></select>
        <button type="submit" class="filterButton">FILTER</button>
    </form>
</div>

<div class="row">
    @if (Model.Events.Count() == 0)
    {
        <text>No events were found.</text>
    }
    else
    {
        <table class="table">
            <thead>
                <tr class="columnHeader">
                    <th></th>
                    <th>DATE</th>
                    <th>NAME</th>
                    <th>ARTIST</th>
                    <th>PRICE</th>
                </tr>
            </thead>
            <tbody>
                @Html.DisplayFor(m => m.Events)
            </tbody>
        </table>
    }
</div>

@*section Widget {
    <partial name="_ShoppingCartWidget" model="@Model.NumberOfItems" />}*@